"""TradeHypothesis schema.

Runbook 78: TradeHypothesis Schema + HypothesisExecutor.

The TradeHypothesis is the atomic unit of the new round-trip model.
It replaces the 3–5 disconnected TriggerConditions that previously encoded
one trade idea across entry + emergency_exit + risk_off + risk_reduce triggers.

Key design constraints:
- stop_price and target_price are REQUIRED at plan compile time.
  The compiler (services/hypothesis_compiler.py) rejects hypotheses where
  these cannot be resolved from structure.stop_anchor_source /
  structure.target_anchor_source at plan generation time.
- rr_ratio is computed by the compiler, not the LLM.
- The HypothesisExecutor (services/hypothesis_executor.py) owns
  stop/target sweep and invalidation logic for hypothesis-mode plans.
- Exit trigger categories (emergency_exit, risk_off, risk_reduce) are
  suppressed by TriggerEngine when hypothesis mode is active for a symbol.
"""
from __future__ import annotations

from typing import Any, Dict, Literal, Optional
from uuid import uuid4

from pydantic import BaseModel, Field, model_validator


class StructureBasis(BaseModel):
    """The structural context that motivates the hypothesis.

    stop_anchor_level and target_anchor_level are resolved at compile time
    from the StructureSnapshot for this symbol. They are stored as absolute
    prices so the executor can sweep price against them without re-lookup.
    """

    model_config = {"extra": "forbid"}

    # Absolute price levels (resolved by compiler)
    key_support: Optional[float] = Field(
        default=None, description="Nearest support level price below entry."
    )
    key_resistance: Optional[float] = Field(
        default=None, description="Nearest resistance level price above entry."
    )
    stop_anchor_level: float = Field(
        description="Absolute stop price (required). Resolved from stop_anchor_source."
    )
    target_anchor_level: float = Field(
        description="Absolute target price (required). Resolved from target_anchor_source."
    )

    # Human-readable provenance strings (LLM-authored, compiler-validated)
    stop_anchor_source: str = Field(
        description="Source for stop anchor. E.g. 'swing_low_2026-03-12', 'htf_daily_low', "
        "'atr_1.5x', 'structure_support_0.0974'. Must be resolvable by the compiler."
    )
    target_anchor_source: str = Field(
        description="Source for target anchor. E.g. 'swing_high_2026-03-10', "
        "'htf_daily_high', 'r_multiple_2', 'structure_resistance_0.1020'."
    )
    structure_notes: Optional[str] = Field(
        default=None,
        description="Plain-text description of the structure. E.g. "
        "'Price consolidating below $0.098 resistance, ATR contracting.'",
    )


class TradeHypothesis(BaseModel):
    """A complete round-trip trade specification.

    Replaces the 3–5 disconnected TriggerConditions that previously encoded
    one trade idea across entry + emergency_exit + risk_off + risk_reduce triggers.

    Lifecycle:
      PENDING → (entry_rule fires) → OPEN → (stop or target swept, or invalidation) → COMPLETED

    The HypothesisExecutor manages this lifecycle. When a hypothesis is OPEN:
    - on_tick(): checks if price crossed stop_price or target_price (fast path).
    - on_bar(): evaluates invalidation_rule.
    - After invalidation_horizon_bars: auto-expires if not yet resolved.
    """

    model_config = {"extra": "forbid"}

    id: str = Field(
        default_factory=lambda: f"hyp_{uuid4().hex[:8]}",
        description="Unique hypothesis ID. Auto-generated by default.",
    )
    symbol: str
    timeframe: str
    direction: Literal["long", "short"]
    confidence_grade: Literal["A", "B", "C"] = Field(
        default="B",
        description="LLM-assigned confidence. A = high conviction, C = speculative.",
    )
    playbook_id: Optional[str] = Field(
        default=None,
        description="Playbook ID that motivated this hypothesis (from SessionIntent or registry).",
    )

    # ── Thesis ────────────────────────────────────────────────────────────────
    thesis: str = Field(
        description="Plain-text trade thesis. E.g. "
        "'POL forming compression below $0.098; expect breakout long on vol burst.'"
    )
    regime_context: Optional[str] = Field(
        default=None,
        description="Market regime at hypothesis creation. E.g. 'range/low_vol'.",
    )
    indicator_basis: str = Field(
        description="Which indicators motivated this. E.g. "
        "'RSI=42 (neutral), ATR contracting (5-bar), ADX=18 (low momentum).'",
    )

    # ── Structure ─────────────────────────────────────────────────────────────
    structure: StructureBasis

    # ── Entry ─────────────────────────────────────────────────────────────────
    entry_rule: str = Field(
        description="DSL expression evaluated by TriggerEngine. "
        "Same syntax as TriggerCondition.entry_rule. "
        "E.g. 'vol_burst and close > donchian_upper_short'.",
    )
    entry_notes: Optional[str] = Field(
        default=None,
        description="Optional rationale for entry timing. Not executed.",
    )

    # ── Exit (inline — no separate exit trigger needed) ───────────────────────
    # stop_price and target_price are REQUIRED at plan time.
    # The compiler raises compile_time_hypothesis_violation if either is missing
    # or directionally inconsistent with entry direction.
    stop_price: float = Field(
        description="Absolute stop price. "
        "For long: must be < current price. For short: must be > current price. "
        "Set from structure.stop_anchor_level by the compiler.",
    )
    target_price: float = Field(
        description="Absolute target price. "
        "For long: must be > current price. For short: must be < current price. "
        "Set from structure.target_anchor_level by the compiler.",
    )
    stop_loss_pct: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Percentage stop fallback. Used only when structural stop cannot be "
        "resolved at runtime (price has moved past structure.stop_anchor_level).",
    )
    trailing_stop_activation_r: Optional[float] = Field(
        default=None,
        ge=0.5,
        description="Activate trailing stop at N×R from entry. "
        "E.g. 1.0 = trail at 1R. None = no trailing stop.",
    )

    # ── Invalidation ──────────────────────────────────────────────────────────
    invalidation_rule: Optional[str] = Field(
        default=None,
        description="DSL expression. When True while position is PENDING, "
        "the hypothesis is invalidated (setup is stale). "
        "Separate from stop: stop is price execution; invalidation is setup staleness.",
    )
    invalidation_horizon_bars: int = Field(
        default=12,
        ge=1,
        description="Max bars before hypothesis auto-expires regardless of price. "
        "Prevents stale PENDING hypotheses from lingering across regime shifts.",
    )

    # ── Compiler-filled (not LLM-authored) ────────────────────────────────────
    rr_ratio: Optional[float] = Field(
        default=None,
        description="Risk-to-reward ratio computed by the compiler: "
        "abs(target_price - entry_estimate) / abs(entry_estimate - stop_price). "
        "entry_estimate = current price at compile time.",
    )
    estimated_bars_to_resolution: Optional[int] = Field(
        default=None,
        ge=1,
        description="LLM forecast for how many bars until resolution. "
        "Informational; measured against actual bars_held for attribution.",
    )

    @model_validator(mode="after")
    def _validate_direction_consistency(self) -> "TradeHypothesis":
        """Check that stop and target are on the correct sides for the declared direction.

        Long:  stop_price < target_price  (stop below entry, target above)
        Short: stop_price > target_price  (stop above entry, target below)

        Full compile-time validation against actual entry price is done by
        HypothesisCompiler. This is a schema-level sanity check only.
        """
        if self.direction == "long" and self.stop_price >= self.target_price:
            raise ValueError(
                f"Hypothesis {self.id} (long): stop_price={self.stop_price} must be "
                f"< target_price={self.target_price}. "
                "Long trades: stop is below entry, target is above entry."
            )
        if self.direction == "short" and self.stop_price <= self.target_price:
            raise ValueError(
                f"Hypothesis {self.id} (short): stop_price={self.stop_price} must be "
                f"> target_price={self.target_price}. "
                "Short trades: stop is above entry, target is below entry."
            )
        return self
